name: Server CI

on:
  push:
    # remove branches-ignore when test failures in server are fixed
    branches-ignore:
      - '**'
  pull_request:
    branches: [ master, development ]
    # remove branches-ignore when test failures in server are fixed
    branches-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: change dir to server
      run: cd server
    - name: Grant execute permission for gradlew
      run: chmod +x server/gradlew
    - name: Build with Gradle
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: cd server && ./gradlew build jacocoTestReport sonarqube --info
